# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '\u7ae0\u8282\u4fe1\u606f', 'verbose_name_plural': '\u7ae0\u8282\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '\u7ae0\u8282\u89c6\u9891', 'verbose_name_plural': '\u7ae0\u8282\u89c6\u9891'},
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[(b'junior', b'\xe5\x88\x9d\xe7\xba\xa7'), (b'middle', b'\xe4\xb8\xad\xe7\xba\xa7'), (b'super', b'\xe9\xab\x98\xe7\xba\xa7')], max_length=10, verbose_name=b'\xe9\x9a\xbe\xe5\xba\xa6\xe7\xad\x89\xe7\xba\xa7'),
        ),
    ]
